import Footer from "@/components/Common/Footer";
import TopNavbar from "@/components/Common/TopNavbar";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import ScreenSize from "./ScreenSize";

const Layout = ({ children, title }) => {
    return (
        <Box>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <Box minH="77px">
                <TopNavbar />
            </Box>
            <Box>{children}</Box>
            <Footer />
        </Box>
    );
};

export default Layout;
